name: Coding Standards

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    name: PHP Coding Standards

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        tools: composer:v2, cs2pr

    - name: Check PHP Version
      run: php -v

    - name: Composer install
      run: composer install --optimize-autoloader --prefer-dist

    - name: Coding Sniffs.
      run: ./vendor/bin/phpcs --report-full --report-checkstyle=${{ runner.temp }}/phpcs-report.xml

    - name: Show PHPCS results in PR
      if: ${{ always() }}
      run: cs2pr ${{ runner.temp }}/phpcs-report.xml
